name: C/C++ CI Ubuntu 18.04 Building vm-exec wasm

on: [push,workflow_dispatch]
env:
  ZLIB_LIBRARY: ${{ env.GITHUB_WORKSPACE }}/wasm-libs/zlib/
  ZLIB_INCLUDE_DIR: ${{ env.GITHUB_WORKSPACE }}/wasm-libs/zlib/
  OPENSSL_ROOT_DIR: $GITHUB_WORKSPACE/wasm-libs/openssl/openssl-1.1.1d/
  OPENSSL_INCLUDE_DIR: $GITHUB_WORKSPACE/wasm-libs/openssl/openssl-1.1.1d/include/
  OPENSSL_CRYPTO_LIBRARY: $GITHUB_WORKSPACE/wasm-libs/openssl/openssl-1.1.1d/libcrypto.a
  OPENSSL_SSL_LIBRARY: $GITHUB_WORKSPACE/wasm-libs/openssl/openssl-1.1.1d/libssl.a
  OPENSSL_LIBRARIES: $OPENSSL_SSL_LIBRARY $OPENSSL_CRYPTO_LIBRARY

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: mymindstorm/setup-emsdk@v11
    - name: Verify emsdk
      run: emcc -v
    - name: Check out repository
      uses: actions/checkout@v2
      with:      
        submodules: 'recursive'
    - name: mkdir
      run: |
        mkdir build
    - name: cmake
      run: | 
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
    - name: cmake vm-exec
      run: |
        cd build
        cmake --build . --target vm-exec
    - name: find & copy wasm files
      run: |
        mkdir wasm-artifacts
        cp --parents build/crypto/vm-exec.wasm build/crypto/vm-exec.js
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-wasm-files
        path: wasm-artifacts
