name: C/C++ CI Ubuntu 18.04 Building vm-exec wasm

on: [push,workflow_dispatch]


jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:      
        submodules: 'recursive'
    - name: cmake (install emsdk)
      run: |
        sudo apt-get install libreadline-dev -y
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        source ./emsdk_env.sh
        echo "emscripten path"
        stat  /home/runner/work/ton/ton/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
        
        cd ..
        mkdir build
        cd build

        echo "running cmake at folder pwd:$pwd"
        cmake -DCMAKE_TOOLCHAIN_FILE=/home/runner/work/ton/ton/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake        -DZLIB_LIBRARY=$GITHUB_WORKSPACE/wasm-libs/zlib-1.2.12/        -DZLIB_INCLUDE_DIR=$GITHUB_WORKSPACE/wasm-libs/zlib-1.2.12/        -DOPENSSL_ROOT_DIR=$GITHUB_WORKSPACE/wasm-libs/openssl/openssl-1.1.1d/        -DOPENSSL_INCLUDE_DIR=$GITHUB_WORKSPACE/wasm-libs/openssl/openssl-1.1.1d/include/        -DOPENSSL_CRYPTO_LIBRARY=$GITHUB_WORKSPACE/wasm-libs/openssl/openssl-1.1.1d/libcrypto.a        -DOPENSSL_SSL_LIBRARY=$GITHUB_WORKSPACE/wasm-libs/openssl/openssl-1.1.1d/libssl.a        -DOPENSSL_LIBRARIES="$GITHUB_WORKSPACE/wasm-libs/openssl/openssl-1.1.1d/libssl.a $GITHUB_WORKSPACE/wasm-libs/openssl/openssl-1.1.1d/libcrypto.a"  ..
                             
    - name: cmake vm-exec
      run: |
        cmake --build . --target vm-exec
    - name: find & copy wasm files
      run: |
        mkdir wasm-artifacts
        cp --parents build/crypto/vm-exec.wasm build/crypto/vm-exec.js
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-wasm-files
        path: wasm-artifacts
