name: C/C++ CI Ubuntu 18.04 Compile

on: [push,workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:      
        submodules: 'recursive'
    - name: Run Cppcheck
      uses: Bedzior/run-cppcheck@master
      with:
        enabled checks: all
        enable inconclusive: true
        generate report: true
    - name: Upload report
      uses: actions/upload-artifact@v1
      with:
        name: report
        path: output
    - name: mkdir
      run: |
        mkdir build
    - name: cmake
      run: | 
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=Emscripten.cmake
    - name: cmake vm-exec
      run: |
        cd build
        cmake --build . --target vm-exec
    - name: find & copy wasm files
      run: |
        mkdir wasm-artifacts
        cp --parents build/crypto/vm-exec.wasm build/crypto/vm-exec.js
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: ton-wasm-files
        path: wasm-artifacts
